spring:
  application:
    name: UberLocationService
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6380}

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://${CLOUD_SERVICE:localhost}:9090/eureka
    instance:
      preferIpAddress: true

