spring:
  application:
    name: UberLocationService
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
    instance:
      preferIpAddress: true

